version: '3.7'
services:
  homework:
    image: jboss/wildfly:latest
    ports:
      - "8080:8080"
      - "9990:9990"
    restart: always
    volumes:
      - ./docker:/opt/jboss/wildfly/standalone/deployments/